name: Back-end Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        ports:
          - "3307:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./db:/docker-entrypoint-initdb.d/:ro
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r app/requirements.txt
        pip install pytest

    - name: Start Flask app
      run: |
        until nc -zv 127.0.0.1 3307
        do
          echo "Waiting for database..."
          sleep 1
        done
        python app/init_db.py  # Si nécessaire, initialisez la base de données
        python app/app.py &   # Lancez l'application Flask en arrière-plan

    - name: Run Tests
      run: |
        pytest test/test_app.py
