name: Back-end Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r app/requirements.txt
        pip install pytest
    - name: Set up MySQL schema and data
      run: |
        mysql -h 127.0.0.1 -P 3307 -u root -proot -e "CREATE DATABASE devopsroles;"
        mysql -h 127.0.0.1 -P 3307 -u root -proot devopsroles < db/init.sql

    - name: Initialize Database
      run: |
        python app/init_db.py

    - name: Run back
      run: |
        python app/app.py &
        sleep 10  # Ajoutez une pause pour permettre au backend de démarrer
    - name: Check backend accessibility
      run: |
        curl -v http://127.0.0.1:5000/api/get_data
    - name: Run Tests
      run: |
        pytest test/test_app.py
