name: Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/compose-action@v2

    - name: Build and run Docker Compose
      run: docker-compose up -d

